apiVersion: v1
kind: PersistentVolume
metadata:
  name: spark-pv1
  namespace: spark1
  labels:
    app: spark
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  hostPath:
    path: /minikube-host
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: spark-pv-claim
  namespace: spark1
  labels:
    app: spark
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 10Gi