version: '3.8'

services:
  spark-master:
    image: bitnami/spark:latest
    environment:
      - SPARK_MODE=master
      - SPARK_MASTER_HOST=spark-master
      - SPARK_MASTER_PORT=7077
      - SPARK_MASTER_WEBUI_PORT=8080
    ports:
      - "8080:8080"
      - "7077:7077"
    volumes:
      - C:/DEVELOPMENT/sparkdocker/spark-events:/tmp/spark-events
  spark-worker:
    image: bitnami/spark:latest
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_WEBUI_PORT=8081
    ports:
      - "8081:8081"
    depends_on:
      - spark-master

  spark-history-server:
    image: bitnami/spark:latest
    environment:
      - SPARK_HISTORY_SERVER_PORT=18080
      - SPARK_HISTORY_SERVER_LOGDIR=/tmp/spark-events
    command: /opt/bitnami/spark/bin/spark-class -Dspark.history.fs.logDirectory=file:/tmp/spark-events -Dspark.history.ui.port=18080 org.apache.spark.deploy.history.HistoryServer
    ports:
      - "18080:18080"
    volumes:
      - C:/DEVELOPMENT/sparkdocker/spark-events:/tmp/spark-events
    depends_on:
      - spark-master
      - spark-worker