apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres
  namespace: airflow
spec:
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  hostPath:
    path: /airflow/airflow
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: data-airflow-postgresql-0
  namespace: airflow
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  volumeName: postgres
  storageClassName: standard
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: airflow-worker-logs
  namespace: airflow
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  hostPath:
    path: /airflow/airflow/logs/worker
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: logs-airflow-worker-0
  namespace: airflow
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeName: airflow-worker-logs
  storageClassName: standard
  volumeMode: Filesystem