apiVersion: v1
kind: Service
metadata:
  name: sftp1
  labels:
    app: sftp1
spec:
  type: NodePort
  selector:
    app: sftp1
  ports:
    - name: sftp
      protocol: TCP
      port: 22
      targetPort: 22
---
apiVersion: v1
kind: Service
metadata:
  name: sftp2
  labels:
    app: sftp2
spec:
  type: NodePort
  selector:
    app: sftp2
  ports:
    - name: sftp
      protocol: TCP
      port: 22
      targetPort: 22