apiVersion: v1
kind: PersistentVolume
metadata:
  name: tomcat-0
spec:
  capacity:
    storage: 4Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  hostPath:
    path: /minikube-host/tomcat0
---