apiVersion: v1
kind: Service
metadata:
  name: broker1-service
  labels:
    app: activemq
    broker: broker1
spec:
  type: NodePort
  selector:
    app: activemq
    broker: broker1
  ports:
    - name: proto
      protocol: TCP
      port: 61616
      targetPort: 61616
      nodePort: 32000
    - name: web
      protocol: TCP
      port: 8161
      targetPort: 8161
      nodePort: 32001
---
apiVersion: v1
kind: Service
metadata:
  name: broker1
  labels:
    app: activemq
    broker: broker1
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app: activemq
    broker: broker1
  ports:
    - name: proto
      protocol: TCP
      port: 61616
      targetPort: 61616
    - name: web
      protocol: TCP
      port: 8161
      targetPort: 8161
---
apiVersion: v1
kind: Service
metadata:
  name: broker2-service
  labels:
    app: activemq
    broker: broker2
spec:
  type: NodePort
  selector:
    app: activemq
    broker: broker2
  ports:
    - name: proto
      protocol: TCP
      port: 61616
      targetPort: 61616
      nodePort: 32002
    - name: web
      protocol: TCP
      port: 8161
      targetPort: 8161
      nodePort: 32003
---
apiVersion: v1
kind: Service
metadata:
  name: broker2
  labels:
    app: activemq
    broker: broker2
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app: activemq
    broker: broker2
  ports:
    - name: proto
      protocol: TCP
      port: 61616
      targetPort: 61616
    - name: web
      protocol: TCP
      port: 8161
      targetPort: 8161
---
apiVersion: v1
kind: Service
metadata:
  name: broker3-service
  labels:
    app: activemq
    broker: broker3
spec:
  type: NodePort
  selector:
    app: activemq
    broker: broker3
  ports:
    - name: proto
      protocol: TCP
      port: 61616
      targetPort: 61616
      nodePort: 32004
    - name: web
      protocol: TCP
      port: 8161
      targetPort: 8161
      nodePort: 32005
---
apiVersion: v1
kind: Service
metadata:
  name: broker3
  labels:
    app: activemq
    broker: broker3
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app: activemq
    broker: broker3
  ports:
    - name: proto
      protocol: TCP
      port: 61616
      targetPort: 61616
    - name: web
      protocol: TCP
      port: 8161
      targetPort: 8161
---
apiVersion: v1
kind: Service
metadata:
  name: broker4-service
  labels:
    app: activemq
    broker: broker4
spec:
  type: NodePort
  selector:
    app: activemq
    broker: broker4
  ports:
    - name: proto
      protocol: TCP
      port: 61616
      targetPort: 61616
      nodePort: 32006
    - name: web
      protocol: TCP
      port: 8161
      targetPort: 8161
      nodePort: 32007
---
apiVersion: v1
kind: Service
metadata:
  name: broker4
  labels:
    app: activemq
    broker: broker4
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app: activemq
    broker: broker4
  ports:
    - name: proto
      protocol: TCP
      port: 61616
      targetPort: 61616
    - name: web
      protocol: TCP
      port: 8161
      targetPort: 8161