apiVersion: v1
kind: Service
metadata:
  name: broker-service
  labels:
    app: activemq
    broker: broker
spec:
  type: NodePort
  selector:
    app: activemq
    broker: broker
  ports:
    - name: proto
      protocol: TCP
      port: 61616
      targetPort: 61616
      nodePort: 32000
    - name: web
      protocol: TCP
      port: 8161
      targetPort: 8161
      nodePort: 32001