apiVersion: v1
kind: Service
metadata:
  name: artemismaster
  labels:
    app: artemis
    broker: master
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app: artemis
    broker: master
  ports:
    - name: proto
      protocol: TCP
      port: 61616
      targetPort: 61616
    - name: web
      protocol: TCP
      port: 8161
      targetPort: 8161
    - name: jgroupsport
      protocol: TCP
      port: 7800
      targetPort: 7800
---
apiVersion: v1
kind: Service
metadata:
  name: artemisslave
  labels:
    app: artemis
    broker: slave
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app: artemis
    broker: slave
  ports:
    - name: proto
      protocol: TCP
      port: 61616
      targetPort: 61616
    - name: web
      protocol: TCP
      port: 8161
      targetPort: 8161
    - name: jgroupsport
      protocol: TCP
      port: 7800
      targetPort: 7800
---
apiVersion: v1
kind: Service
metadata:
  name: artemismaster-nodeport
  labels:
    app: artemis
    broker: master
spec:
  type: NodePort
  selector:
    app: artemis
    broker: master
  ports:
    - name: proto
      protocol: TCP
      port: 61616
      targetPort: 61616
    - name: web
      protocol: TCP
      port: 8161
      targetPort: 8161
---
apiVersion: v1
kind: Service
metadata:
  name: artemisslave-nodeport
  labels:
    app: artemis
    broker: slave
spec:
  type: NodePort
  selector:
    app: artemis
    broker: slave
  ports:
    - name: proto
      protocol: TCP
      port: 61616
      targetPort: 61616
    - name: web
      protocol: TCP
      port: 8161
      targetPort: 8161
---
apiVersion: v1
kind: Service
metadata:
  name: dns-server
  labels:
    k8s-app: dns-server
spec:
  type: ClusterIP
  clusterIP: None
  selector:
     k8s-app: dns-server
  ports:
    - name: proto
      protocol: TCP
      port: 53
      targetPort: 53
    - name: web
      protocol: TCP
      port: 5380
      targetPort: 5380
---
apiVersion: v1
kind: Service
metadata:
  name: dns-server-nodeport
  labels:
    k8s-app: dns-server
spec:
  type: NodePort
  selector:
     k8s-app: dns-server
  ports:
    - name: proto
      protocol: TCP
      port: 53
      targetPort: 53
    - name: web
      protocol: TCP
      port: 5380
      targetPort: 5380