apiVersion: "sparkoperator.k8s.io/v1beta2"
kind: SparkApplication
metadata:
  name: spark-pi1
  namespace: default
spec:
  type: Scala
  mode: cluster
  image: "apache/spark:3.5.0"
  imagePullPolicy: Always
  mainClass: org.apache.spark.examples.SparkPi
  mainApplicationFile: "local:///mnt/spark/work/spark-examples.jar"
  sparkVersion: "3.5.0"
  restartPolicy:
    type: Never
  volumes:
    - name: test-volume
      hostPath:
        path: "/minikube-host"
        type: Directory
  driver:
    cores: 1
    coreLimit: "1200m"
    memory: "512m"
    labels:
      app: spark
      version: 3.5.0
    serviceAccount: spark-operator-spark
    volumeMounts:
      - name: test-volume
        mountPath: /mnt/spark/work
  executor:
    cores: 1
    instances: 4
    memory: "512m"
    labels:
      app: spark
      version: 3.5.0
    serviceAccount: spark-operator-spark
    volumeMounts:
      - name: test-volume
        mountPath: /mnt/spark/work