{{- $endIndex := (int (add (int (toString .Values.startIndex)) (int (toString .Values.ndbReplicaCount)))) }}
{{- $rangestep := untilStep (int .Values.startIndex) $endIndex (int 1) -}}
{{- range $index, $i := $rangestep }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: ndbd-pv{{ $i }}
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  hostPath:
    path: /minikube-host/mysql{{ $i }}
---
{{- end }}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: management
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  hostPath:
    path: /minikube-host/management
---
{{- $rangestep := untilStep (int .Values.mysqlStartIndex) (int .Values.mysqlEndIndex) (int 1) -}}
{{- range $index, $i := $rangestep }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv{{ $i }}
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  hostPath:
    path: /minikube-host/mysql{{ $i }}
---
{{- end }}