apiVersion: v1
kind: Service
metadata:
  name: artemismaster-0
  labels:
    app: artemis
    broker: master
spec:
  type: ClusterIP
  selector:
    app: artemis
    broker: master
  ports:
    - name: proto
      protocol: TCP
      port: 61616
      targetPort: 61616
    - name: web
      protocol: TCP
      port: 8161
      targetPort: 8161
    - name: jgroupsport
      protocol: TCP
      port: 7800
      targetPort: 7800
---
apiVersion: v1
kind: Service
metadata:
  name: artemisslave-0
  labels:
    app: artemis
    broker: slave
spec:
  type: ClusterIP
  selector:
    app: artemis
    broker: slave
  ports:
    - name: proto
      protocol: TCP
      port: 61617
      targetPort: 61617
    - name: web
      protocol: TCP
      port: 8161
      targetPort: 8161
    - name: jgroupsport
      protocol: TCP
      port: 7800
      targetPort: 7800
---
apiVersion: v1
kind: Service
metadata:
  name: artemismaster-nodeport
  labels:
    app: artemis
    broker: master
spec:
  type: NodePort
  selector:
    app: artemis
    broker: master
  ports:
    - name: proto
      protocol: TCP
      port: 61616
      targetPort: 61616
    - name: web
      protocol: TCP
      port: 8161
      targetPort: 8161
---
apiVersion: v1
kind: Service
metadata:
  name: artemisslave-nodeport
  labels:
    app: artemis
    broker: slave
spec:
  type: NodePort
  selector:
    app: artemis
    broker: slave
  ports:
    - name: proto
      protocol: TCP
      port: 61617
      targetPort: 61617
    - name: web
      protocol: TCP
      port: 8161
      targetPort: 8161