apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-primary
spec:
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  hostPath:
    path: /minikube-host/primary
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-secondary1
spec:
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  hostPath:
    path: /minikube-host/secondary1
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-secondary2
spec:
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  hostPath:
    path: /minikube-host/secondary2
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-secondary3
spec:
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  hostPath:
    path: /minikube-host/secondary3